In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# read in the raw data from the github url

df = pd.read_csv("https://raw.githubusercontent.com/suneel0101/lesson-plan/master/crunchbase_monthly_export.csv")
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN

#### 1. Clean the data. Use .apply and lambda functions where you can

In [3]:
# rename the columns to remove spaces and extra characters
print list(df.columns)

['permalink', 'name', 'homepage_url', 'category_list', ' market ', ' funding_total_usd ', 'status', 'country_code', 'state_code', 'region', 'city', 'funding_rounds', 'founded_at', 'founded_month', 'founded_quarter', 'founded_year', 'first_funding_at', 'last_funding_at', 'Unnamed: 18']

In [4]:
new_cols = ['permalink', 'name', 'homepage_url', 'category_list', 'market', 'funding_total_usd', 'status', 'country_code', 'state_code', 'region', 'city', 'funding_rounds', 'founded_at', 'founded_month', 'founded_quarter', 'founded_year', 'first_funding_at', 'last_funding_at', 'Unnamed: 18']
df.columns = new_cols

In [5]:
# convert the funding, year founded, and funding_rounds columns to numeric values
custom_null = df['funding_total_usd'][9]
custom_null

' -   '

In [6]:
df['funding_total_usd'].replace(custom_null, np.nan, inplace=True)

def _dollars_to_int(x):
    try:
        y = (str(x)).replace(',','')
        return int(y)
    except:
        pass
        
df['funding_total_usd'] = df['funding_total_usd'].apply(_dollars_to_int)

In [7]:
# convert category_list so that each cell is a list of categories
df.category_list = df.category_list.apply(lambda x: (str(x)).split('|')[1:-1])
df.category_list

0                  [Credit, Technology, Services, Finance]
1            [Entertainment, Politics, Social Media, News]
2                                                  [Games]
3                                  [Publishing, Education]
4        [Electronics, Guides, Coffee, Restaurants, Mus...
5                                               [Software]
6                                               [Software]
7                                            [Advertising]
8                                            [Curated Web]
9                                               [Software]
10                                             [Analytics]
11                                            [E-Commerce]
12                        [Entertainment, Games, Software]
13                                   [Health and Wellness]
14                                   [Health and Wellness]
15                                           [Real Estate]
16                                            [E-Commerce]
17                                                [Search]
18                         [Marketplaces, Art, E-Commerce]
19                                           [Curated Web]
20                                           [Curated Web]
21                                           [Curated Web]
22                         [Local Businesses, Restaurants]
23                                          [Media, Games]
24                                           [Hospitality]
25                                             [Education]
26                                             [Analytics]
27                                              [Software]
28                                           [Curated Web]
29          [Social Commerce, E-Commerce, Mobile Commerce]
                               ...
44920                                [Messaging, Software]
44921                                             [Mobile]
44922                                           [Software]
44923    [Meeting Software, Polling, Surveys, Android, ...
44924                                               [News]
44925           [Social Network Media, Networking, Mobile]
44926                       [Medical Devices, Health Care]
44927                                        [SMS, Mobile]
44928                                      [Manufacturing]
44929    [Design, Health and Wellness, Hardware + Softw...
44930    [Data Security, Automotive, Portals, Education...
44931                                         [E-Commerce]
44932                      [Hardware, Hardware + Software]
44933                                      [Biotechnology]
44934                                      [Biotechnology]
44935                    [Networking, Web Hosting, Mobile]
44936                [Knowledge Management, Crowdsourcing]
44937    [Social Business, Enterprise 2.0, Cloud Comput...
44938    [Technology, Facebook Applications, Networking...
44939                                      [Biotechnology]
44940                                           [Software]
44941                                      [Biotechnology]
44942                                      [Biotechnology]
44943                                         [E-Commerce]
44944                                      [Biotechnology]
44945    [Analytics, Gamification, Developer APIs, iOS,...
44946                                [Enterprise Software]
44947     [Web Development, Advertising, Wireless, Mobile]
44948                                              [Games]
44949                                [Enterprise Software]
Name: category_list, dtype: object

In [8]:
# use value_counts on market, status, and country_code to check for any repeats or misnamed entries

In [18]:
# BONUS: convert the date columns to appropriate datetime objects
%time df.founded_at = df.founded_at.apply(lambda x: pd.to_datetime(x))
%time df.founded_at = df.founded_at.apply(lambda x: pd.to_datetime(x))
%time df.founded_month = df.founded_month.apply(lambda x: pd.Period(x, freq= "M"))
%time df.founded_quarter = df.founded_quarter.apply(lambda x: pd.Period(x, freq= "Q"))

def _convert_time(x):
    try:
        return pd.to_datetime(x)
    except:
        return np.nan

%time df.last_funding_at = df.last_funding_at.apply(_convert_time)
%time df.first_funding_at = df.first_funding_at.apply(_convert_time)

CPU times: user 300 ms, sys: 3.93 ms, total: 304 ms
Wall time: 305 ms
CPU times: user 371 ms, sys: 36.3 ms, total: 407 ms
Wall time: 382 ms

#### 2. Using isnull(), take a subset of the dataframe that has no founded at date

In [10]:
df[df.founded_at.isnull()].head(2)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,"[Credit, Technology, Services, Finance]",Credit,750000.0,NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaT,NaT,NaT,NaN,2010-01-01,2010-01-01,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,[Games],Games,4000000.0,operating,USA,CA,Los Angeles,Los Angeles,2,NaT,NaT,NaT,NaN,2010-06-04,2010-09-23,NaN

#### 3. Create a new column, founded_year_x, that's a copy of founded_year. Then, replace all the missing values with either the mean , mode, or median of that column. 
Add a note explaining which statistic you picked and why:

In [11]:
df['founded_year_x'] = df['founded_year'].fillna(np.median)

#### 4. Take a subset of US-based companies using boolean selection

In [12]:
df[df.country_code == 'USA'].head(2)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18,founded_year_x
1,/organization/waywire,#waywire,http://www.waywire.com,"[Entertainment, Politics, Social Media, News]",Entertainment,1750000.0,acquired,USA,NY,New York City,New York,1,2012-06-01,2012-06,2012Q2,2012.0,2012-06-30,2012-06-30,NaN,2012
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,[Games],Games,4000000.0,operating,USA,CA,Los Angeles,Los Angeles,2,NaT,NaT,NaT,NaN,2010-06-04,2010-09-23,NaN,<function median at 0x10668e140>

#### 5. Create a pivot table showing total, mean, and median funding amount by year

In [13]:
df.pivot_table(index='founded_year', values = 'funding_total_usd', \
               aggfunc=(np.mean, np.median, sum, lambda x: len(x.unique())))

                      mean       median           sum  <lambda>
founded_year
1900.0        2.365031e+07   23650306.0  2.365031e+07       1.0
1902.0        3.100000e+06    3100000.0  3.100000e+06       1.0
1903.0        9.300000e+06    9300000.0  9.300000e+06       1.0
1906.0        2.275600e+08   10000000.0  1.137800e+09       5.0
1908.0        5.814700e+06    5814700.0  5.814700e+06       1.0
1910.0        1.000000e+05     100000.0  1.000000e+05       2.0
1911.0        2.400000e+06    2400000.0  2.400000e+06       1.0
1912.0        3.392500e+07    6100000.0  1.357000e+08       4.0
1913.0        5.057539e+07   50575389.5  1.011508e+08       2.0
1914.0        1.665000e+07   16650000.0  3.330000e+07       2.0
1917.0        3.000000e+08  300000000.0  3.000000e+08       1.0
1918.0        1.570000e+05     157000.0  1.570000e+05       1.0
1919.0        2.640352e+07   34610561.0  7.921056e+07       3.0
1920.0        2.500000e+06    2500000.0  2.500000e+06       1.0
1921.0        1.752400e+07   17524000.0  3.504800e+07       2.0
1922.0        7.190000e+07    6700000.0  2.157000e+08       4.0
1923.0        1.972618e+07   19726183.0  3.945237e+07       2.0
1924.0        1.741866e+08   35000000.0  8.709330e+08       5.0
1925.0        1.543200e+05     154320.0  1.543200e+05       1.0
1926.0        4.035000e+05     403500.0  8.070000e+05       2.0
1928.0        3.127000e+07   12365000.0  1.250800e+08       4.0
1929.0                 NaN          NaN           NaN       1.0
1930.0        8.184388e+07    7999399.0  4.092194e+08       5.0
1933.0        1.507680e+05     150768.0  1.507680e+05       1.0
1934.0        6.000000e+07   60000000.0  1.200000e+08       2.0
1936.0                 NaN          NaN           NaN       1.0
1937.0        7.500000e+04      75000.0  1.500000e+05       2.0
1939.0        7.500000e+06    7500000.0  7.500000e+06       1.0
1941.0        1.414100e+06    1414100.0  1.414100e+06       1.0
1943.0        1.772000e+07   17720000.0  1.772000e+07       1.0
...                    ...          ...           ...       ...
1985.0        5.316090e+07    8276559.0  2.977010e+09      56.0
1986.0        2.861501e+07   14065000.0  1.259061e+09      43.0
1987.0        3.113645e+07   10000000.0  1.681369e+09      49.0
1988.0        1.869189e+07    8509755.5  1.009362e+09      50.0
1989.0        3.243044e+07   10295200.0  2.140409e+09      64.0
1990.0        2.139882e+07    6334832.5  1.412322e+09      63.0
1991.0        3.975768e+07    8000000.0  2.902310e+09      67.0
1992.0        2.616598e+07    6000000.0  2.433436e+09      85.0
1993.0        3.822720e+07    8000000.0  4.090310e+09      94.0
1994.0        2.373488e+07   11260000.0  2.943125e+09     106.0
1995.0        3.922696e+07    9000000.0  6.903944e+09     154.0
1996.0        3.061159e+07    8206814.0  7.714121e+09     204.0
1997.0        2.520422e+07   10000000.0  7.737695e+09     240.0
1998.0        3.151053e+07    9000000.0  1.153285e+10     287.0
1999.0        2.930732e+07   11000000.0  1.919629e+10     464.0
2000.0        2.620316e+07   10966500.0  2.033366e+10     546.0
2001.0        3.015135e+07   10000000.0  1.953807e+10     490.0
2002.0        2.779761e+07   10000000.0  1.931934e+10     525.0
2003.0        3.223257e+07    9789999.5  2.739768e+10     641.0
2004.0        3.382858e+07   10000000.0  3.386241e+10     739.0
2005.0        2.923902e+07    7625000.0  3.637334e+10     866.0
2006.0        2.191151e+07    5600000.0  3.396284e+10    1021.0
2007.0        2.187318e+07    3800000.0  4.341825e+10    1220.0
2008.0        1.417706e+07    2800000.0  2.746097e+10    1157.0
2009.0        1.163791e+07    1725000.0  2.794263e+10    1363.0
2010.0        7.794701e+06    1250000.0  2.369589e+10    1480.0
2011.0        5.456323e+06    1000000.0  2.076677e+10    1666.0
2012.0        4.078702e+06     500009.0  1.544604e+10    1519.0
2013.0        2.874694e+06     257554.0  7.123492e+09     939.0
2014.0        2.086863e+06     100000.0  9.849995e+08     212.0

[101 rows x 4 columns]

### Optional: some of these year values seem fishy. Look at the companies with founded_year dates before 1910. Soda Stream definitely wasn't founded in 1906. Reassign founded year as an interpretation of the founded_at column.

In [19]:
df[df.founded_year < 1910].head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18,founded_year_x,founded_year_x2
7164,/organization/ces-acquisition-corp,CES Acquisition Corp,http://www.calverteducation.com,[],NaN,6000000.0,operating,USA,MD,Baltimore,...,2,2006-01-01,1906-01,1906Q1,1906.0,2013-04-10,2014-02-14,NaN,1906,2006.0
20336,/organization/justrite-manufacturing,Justrite Manufacturing,http://www.justritemfg.com,[],NaN,14800000.0,operating,USA,IL,"Springfield, Illinois",...,1,2006-01-01,1906-01,1906Q1,1906.0,2014-02-20,2014-02-20,NaN,1906,2006.0
21779,/organization/liberator-medical-supply,Liberator Medical Supply,http://liberatormedical.com,[Health and Wellness],Health and Wellness,7000000.0,operating,USA,FL,Florida's Treasure Coast,...,1,2006-01-01,1906-01,1906Q1,1906.0,2010-03-11,2010-03-11,NaN,1906,2006.0
28281,/organization/owensboro-grain,Owensboro Grain,http://www.owensborograin.com,[Manufacturing],Manufacturing,10000000.0,operating,USA,KS,NaN,...,1,2006-01-01,1906-01,1906Q1,1906.0,2012-08-16,2012-08-16,NaN,1906,2006.0
35847,/organization/sodastream,SodaStream,http://www.sodastream.com,"[Consumer Electronics, Entertainment, Health a...",Consumer Electronics,9300000.0,operating,ISR,NaN,Asia,...,1,2003-01-01,1903-01,1903Q1,1903.0,2008-08-07,2008-08-07,NaN,1903,2003.0

In [15]:
#Note: the x.year extracts the year from a pd Timestamp
df['founded_year_x2'] = df.founded_at.apply(lambda x: float(x.year))

In [16]:
#Limit the results to values between 1985 and 2016
df2 = df[(df.founded_year_x2 > 1985) & (df.founded_year_x2 < 2016)]

df2.pivot_table(index='founded_year_x2', values = 'funding_total_usd', \
               aggfunc=(np.mean, np.median, sum, lambda x: len(x.unique())))

                         mean      median           sum  <lambda>
founded_year_x2
1986.0           2.861501e+07  14065000.0  1.259061e+09      43.0
1987.0           3.113645e+07  10000000.0  1.681369e+09      49.0
1988.0           1.869189e+07   8509755.5  1.009362e+09      50.0
1989.0           3.243044e+07  10295200.0  2.140409e+09      64.0
1990.0           2.139882e+07   6334832.5  1.412322e+09      63.0
1991.0           3.975768e+07   8000000.0  2.902310e+09      67.0
1992.0           2.616598e+07   6000000.0  2.433436e+09      85.0
1993.0           3.822720e+07   8000000.0  4.090310e+09      94.0
1994.0           2.373488e+07  11260000.0  2.943125e+09     106.0
1995.0           3.922696e+07   9000000.0  6.903944e+09     154.0
1996.0           3.061159e+07   8206814.0  7.714121e+09     204.0
1997.0           2.520422e+07  10000000.0  7.737695e+09     240.0
1998.0           3.151053e+07   9000000.0  1.153285e+10     287.0
1999.0           2.930732e+07  11000000.0  1.919629e+10     464.0
2000.0           2.756804e+07  11107539.5  2.155821e+10     550.0
2001.0           3.015135e+07  10000000.0  1.953807e+10     490.0
2002.0           2.776212e+07  10000000.0  1.932244e+10     526.0
2003.0           3.220562e+07   9779999.0  2.740698e+10     642.0
2004.0           3.382858e+07  10000000.0  3.386241e+10     739.0
2005.0           2.923902e+07   7625000.0  3.637334e+10     866.0
2006.0           2.257276e+07   5642292.0  3.510064e+10    1023.0
2007.0           2.187318e+07   3800000.0  4.341825e+10    1220.0
2008.0           1.417275e+07   2800000.0  2.746678e+10    1158.0
2009.0           1.163791e+07   1725000.0  2.794263e+10    1363.0
2010.0           7.792171e+06   1250000.0  2.369599e+10    1480.0
2011.0           5.455520e+06   1000000.0  2.076917e+10    1666.0
2012.0           4.110194e+06    508295.0  1.558174e+10    1521.0
2013.0           2.913162e+06    257817.5  7.224642e+09     941.0
2014.0           2.148311e+06    100000.0  1.018300e+09     214.0

#### 6. Create a pivot table showing total, mean and median funding amount by market

In [17]:
df.pivot_table(index='market', values='funding_total_usd', \
              aggfunc=(np.mean, np.median, sum, lambda x: len(x.unique())))
#This lambda function represents count of values

,mean,median,sum,<lambda>
market,,,,
3D,9.189392e+06,1200000.0,5.513635e+08,57.0
3D Printing,1.967000e+06,2000000.0,9.835000e+06,6.0
3D Technology,NaN,NaN,NaN,1.0
Accounting,1.989102e+07,2592000.0,1.233243e+09,56.0
Active Lifestyle,4.100833e+06,275000.0,2.460500e+07,6.0
Ad Targeting,2.486977e+07,3800000.0,1.318098e+09,48.0
Advanced Materials,5.550000e+07,55500000.0,5.550000e+07,2.0
Adventure Travel,1.706032e+05,145000.0,1.876635e+06,10.0
Advertising,1.195821e+07,2077974.5,2.011370e+10,893.0
Advertising Exchanges,2.648729e+07,3450673.0,7.946187e+07,3.0
Advertising Networks,8.773903e+05,375000.0,8.773903e+06,9.0
Advertising Platforms,9.715235e+07,1917833.0,1.068676e+09,11.0
Advice,4.504138e+06,477985.0,8.107449e+07,17.0
Aerospace,1.616990e+07,1835000.0,3.719076e+08,23.0
Agriculture,1.115717e+07,1200000.0,3.347152e+08,27.0
Algorithms,2.643819e+06,645000.0,2.643819e+07,11.0
All Markets,3.220442e+06,1028855.0,4.186574e+07,14.0
All Students,5.884268e+07,368500.0,3.177505e+09,48.0
Alternative Medicine,6.200000e+06,6200000.0,6.200000e+06,1.0
Alumni,2.156835e+06,403340.0,1.294101e+07,6.0
Analytics,1.187397e+07,2500000.0,1.198083e+10,632.0
Android,7.603216e+06,871216.5,2.691538e+09,238.0
Angels,1.948246e+06,1525000.0,1.558597e+07,8.0
Animal Feed,3.832500e+06,3832500.0,7.665000e+06,3.0
App Marketing,7.128752e+06,2252425.0,2.637638e+08,36.0
App Stores,6.060544e+06,1108500.0,1.333320e+08,21.0
Application Performance Monitoring,2.009890e+07,11100000.0,6.029670e+07,3.0
Application Platforms,2.433425e+07,5510610.5,1.460055e+08,6.0
Apps,5.931559e+06,843350.0,2.331103e+09,249.0
Aquaculture,7.500000e+05,750000.0,7.500000e+05,1.0
...,...,...,...,...
Therapeutics,6.300000e+06,6300000.0,6.300000e+06,1.0
Ticketing,5.259272e+06,5049800.0,2.629636e+07,5.0
Tourism,9.143131e+06,154392.0,2.742939e+07,3.0
Toys,3.600000e+05,360000.0,3.600000e+05,1.0
Tracking,7.705000e+06,3270000.0,3.082000e+07,4.0
Trading,4.000000e+04,40000.0,4.000000e+04,1.0
Transportation,5.499976e+06,250000.0,6.049973e+07,12.0
Travel,1.495166e+07,1740000.0,2.586637e+09,124.0
Travel & Tourism,3.799846e+06,487193.0,1.519939e+07,5.0
User Experience Design,2.500000e+04,25000.0,2.500000e+04,1.0
Utilities,3.875395e+07,3650000.0,1.550158e+08,5.0
Venture Capital,1.800000e+07,18000000.0,1.800000e+07,1.0
Veterinary,NaN,NaN,NaN,1.0
Video,5.450000e+06,1050000.0,1.635000e+07,4.0
Video Games,2.182811e+06,1793650.5,1.309687e+07,7.0
Video Streaming,1.250000e+06,1250000.0,2.500000e+06,3.0
Video on Demand,6.389987e+06,6389987.0,6.389987e+06,1.0
VoIP,1.175000e+07,11750000.0,2.350000e+07,3.0
Web Design,5.400000e+06,5400000.0,5.400000e+06,2.0
Web Development,9.167600e+06,5500000.0,3.667040e+07,4.0
Web Hosting,2.738112e+07,9470000.0,9.501247e+09,273.0
Web Tools,4.000000e+06,4000000.0,4.000000e+06,1.0
Weddings,3.762500e+06,3762500.0,7.525000e+06,3.0
Wholesale,1.260228e+06,1260228.0,1.260228e+06,1.0
Wine And Spirits,1.910000e+06,1000000.0,5.730000e+06,4.0
Wireless,1.961250e+07,19612500.0,3.922500e+07,2.0
iOS,7.901242e+05,246500.0,7.901242e+06,11.0
iPad,1.850270e+06,944814.0,2.775405e+07,16.0
iPhone,2.372621e+06,875000.0,7.592388e+07,31.0
mHealth,1.219390e+05,121939.0,2.438780e+05,2.0